# 1. 운영체제 및 프로그램 설치
# FROM ubuntu:22.04

# RUN sudo apt install nodejs
# RUN sudo npm install -g yarn

# 1. 운영체제 및 프로그램 설치(이미 리눅스, node, npm, yarn까지 모두 깔려 있는 컴퓨터 다운로드하기)
FROM node:14

# 2. 내 컴퓨터에 있는 폴더나 파일을 도커 컴퓨터 안으로 복사하기
RUN mkdir qqq
COPY ./index.js /qqq/index.js
WORKDIR /qqq/

# 3. 도커안에서 index.js 실행시키기
CMD node index.js